/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as DropinImport } from './routes/dropin'
import { Route as CreateDropinImport } from './routes/createDropin'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as CreateDropinIndexImport } from './routes/createDropin/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ProfileLogoutImport } from './routes/profile/logout'
import { Route as ProfileGroupChatImport } from './routes/profile/group-chat'
import { Route as CreateDropinDescriptionEditorImport } from './routes/createDropin/DescriptionEditor'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DropinRoute = DropinImport.update({
  id: '/dropin',
  path: '/dropin',
  getParentRoute: () => rootRoute,
} as any)

const CreateDropinRoute = CreateDropinImport.update({
  id: '/createDropin',
  path: '/createDropin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)

const CreateDropinIndexRoute = CreateDropinIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateDropinRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)

const ProfileLogoutRoute = ProfileLogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ProfileRoute,
} as any)

const ProfileGroupChatRoute = ProfileGroupChatImport.update({
  id: '/group-chat',
  path: '/group-chat',
  getParentRoute: () => ProfileRoute,
} as any)

const CreateDropinDescriptionEditorRoute =
  CreateDropinDescriptionEditorImport.update({
    id: '/DescriptionEditor',
    path: '/DescriptionEditor',
    getParentRoute: () => CreateDropinRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/createDropin': {
      id: '/createDropin'
      path: '/createDropin'
      fullPath: '/createDropin'
      preLoaderRoute: typeof CreateDropinImport
      parentRoute: typeof rootRoute
    }
    '/dropin': {
      id: '/dropin'
      path: '/dropin'
      fullPath: '/dropin'
      preLoaderRoute: typeof DropinImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/createDropin/DescriptionEditor': {
      id: '/createDropin/DescriptionEditor'
      path: '/DescriptionEditor'
      fullPath: '/createDropin/DescriptionEditor'
      preLoaderRoute: typeof CreateDropinDescriptionEditorImport
      parentRoute: typeof CreateDropinImport
    }
    '/profile/group-chat': {
      id: '/profile/group-chat'
      path: '/group-chat'
      fullPath: '/profile/group-chat'
      preLoaderRoute: typeof ProfileGroupChatImport
      parentRoute: typeof ProfileImport
    }
    '/profile/logout': {
      id: '/profile/logout'
      path: '/logout'
      fullPath: '/profile/logout'
      preLoaderRoute: typeof ProfileLogoutImport
      parentRoute: typeof ProfileImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof ProfileImport
    }
    '/createDropin/': {
      id: '/createDropin/'
      path: '/'
      fullPath: '/createDropin/'
      preLoaderRoute: typeof CreateDropinIndexImport
      parentRoute: typeof CreateDropinImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof ProfileImport
    }
  }
}

// Create and export the route tree

interface CreateDropinRouteChildren {
  CreateDropinDescriptionEditorRoute: typeof CreateDropinDescriptionEditorRoute
  CreateDropinIndexRoute: typeof CreateDropinIndexRoute
}

const CreateDropinRouteChildren: CreateDropinRouteChildren = {
  CreateDropinDescriptionEditorRoute: CreateDropinDescriptionEditorRoute,
  CreateDropinIndexRoute: CreateDropinIndexRoute,
}

const CreateDropinRouteWithChildren = CreateDropinRoute._addFileChildren(
  CreateDropinRouteChildren,
)

interface ProfileRouteChildren {
  ProfileGroupChatRoute: typeof ProfileGroupChatRoute
  ProfileLogoutRoute: typeof ProfileLogoutRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileGroupChatRoute: ProfileGroupChatRoute,
  ProfileLogoutRoute: ProfileLogoutRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createDropin': typeof CreateDropinRouteWithChildren
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/createDropin/DescriptionEditor': typeof CreateDropinDescriptionEditorRoute
  '/profile/group-chat': typeof ProfileGroupChatRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/createDropin/': typeof CreateDropinIndexRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/createDropin/DescriptionEditor': typeof CreateDropinDescriptionEditorRoute
  '/profile/group-chat': typeof ProfileGroupChatRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/createDropin': typeof CreateDropinIndexRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/createDropin': typeof CreateDropinRouteWithChildren
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/createDropin/DescriptionEditor': typeof CreateDropinDescriptionEditorRoute
  '/profile/group-chat': typeof ProfileGroupChatRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/createDropin/': typeof CreateDropinIndexRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/createDropin'
    | '/dropin'
    | '/login'
    | '/profile'
    | '/signup'
    | '/createDropin/DescriptionEditor'
    | '/profile/group-chat'
    | '/profile/logout'
    | '/profile/settings'
    | '/createDropin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dropin'
    | '/login'
    | '/signup'
    | '/createDropin/DescriptionEditor'
    | '/profile/group-chat'
    | '/profile/logout'
    | '/profile/settings'
    | '/createDropin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/createDropin'
    | '/dropin'
    | '/login'
    | '/profile'
    | '/signup'
    | '/createDropin/DescriptionEditor'
    | '/profile/group-chat'
    | '/profile/logout'
    | '/profile/settings'
    | '/createDropin/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateDropinRoute: typeof CreateDropinRouteWithChildren
  DropinRoute: typeof DropinRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateDropinRoute: CreateDropinRouteWithChildren,
  DropinRoute: DropinRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/createDropin",
        "/dropin",
        "/login",
        "/profile",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/createDropin": {
      "filePath": "createDropin.tsx",
      "children": [
        "/createDropin/DescriptionEditor",
        "/createDropin/"
      ]
    },
    "/dropin": {
      "filePath": "dropin.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx",
      "children": [
        "/profile/group-chat",
        "/profile/logout",
        "/profile/settings",
        "/profile/"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/createDropin/DescriptionEditor": {
      "filePath": "createDropin/DescriptionEditor.tsx",
      "parent": "/createDropin"
    },
    "/profile/group-chat": {
      "filePath": "profile/group-chat.tsx",
      "parent": "/profile"
    },
    "/profile/logout": {
      "filePath": "profile/logout.tsx",
      "parent": "/profile"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx",
      "parent": "/profile"
    },
    "/createDropin/": {
      "filePath": "createDropin/index.tsx",
      "parent": "/createDropin"
    },
    "/profile/": {
      "filePath": "profile/index.tsx",
      "parent": "/profile"
    }
  }
}
ROUTE_MANIFEST_END */
