/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DropinImport } from './routes/dropin'
import { Route as CreateDropinImport } from './routes/createDropin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DropinRoute = DropinImport.update({
  id: '/dropin',
  path: '/dropin',
  getParentRoute: () => rootRoute,
} as any)

const CreateDropinRoute = CreateDropinImport.update({
  id: '/createDropin',
  path: '/createDropin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/createDropin': {
      id: '/createDropin'
      path: '/createDropin'
      fullPath: '/createDropin'
      preLoaderRoute: typeof CreateDropinImport
      parentRoute: typeof rootRoute
    }
    '/dropin': {
      id: '/dropin'
      path: '/dropin'
      fullPath: '/dropin'
      preLoaderRoute: typeof DropinImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createDropin': typeof CreateDropinRoute
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createDropin': typeof CreateDropinRoute
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/createDropin': typeof CreateDropinRoute
  '/dropin': typeof DropinRoute
  '/login': typeof LoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createDropin' | '/dropin' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createDropin' | '/dropin' | '/login'
  id: '__root__' | '/' | '/createDropin' | '/dropin' | '/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateDropinRoute: typeof CreateDropinRoute
  DropinRoute: typeof DropinRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateDropinRoute: CreateDropinRoute,
  DropinRoute: DropinRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/createDropin",
        "/dropin",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/createDropin": {
      "filePath": "createDropin.tsx"
    },
    "/dropin": {
      "filePath": "dropin.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
